baseURL = 'https://ruppec.github.io/'
languageCode = 'en-us'
title = 'Interactive Visualizations of Projective Varieties in Spherical Geometry'
theme = 'HugoTeX'

enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Params]
   darkmode = true  # Set to true to enforce dark mode
  # lightmode = true  # Set to true to enforce light mode

[Params.Author]
   name = "Katie Hess, Charlie Ruppe, and Jake Schaefer"
   abstract = """
Many mathematical theorems are clarified by thinking in projective space, where
so-called \"points at infinity\" are added to complete the geometry. Often these
points at infinity are left out of drawings, with their relation to the other
points and to each other suggested rather than directly illustrated. Yet to an
observer living inside of projective space, these points at infinity would be
geometrically indistinguishable from any other point. In this work, we present a
real-time rendering framework for the intrinsic visualization of 3D real
projective space by ray marching directly on the 3-sphere. Leveraging this
technique, we observe several properties that are most elegantly stated for
projective space. We demonstrate our library's capabilities through visualizing
the geometry of symmetric cubic surfaces and families of cubic curves on quartic
surfaces, as well as how they manifest in this unbiased, personified view.
   """


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          inline = [['$', '$']]
          block = [['$$', '$$']]
  [markup.highlight]
    style = "paraiso-dark"  # Syntax highlighting style